name: Get ROCKs modified and run integration workflow

# On pull_request, we:
# * always build the rocks
# * always run tests

on:
  on_pull_request:

jobs:
  get-all-rock-paths:
    name: Get all rockcraft.yaml paths
    runs-on: ubuntu-22.04
    outputs:
      paths: ${{ steps.find.outputs.paths}}
    steps:
      - name: Get all rockcraft.yaml paths using find
        id: find
        run: |
          paths=$(find ./ -name "rockcraft.yaml" -printf "%h:\n  - '%h/**'\n" | sed 's/\.\///g')
          echo "paths=${paths}" >> $GITHUB_OUTPUT

  changes:
    name: Get paths for ROCKs affected by PR
    needs: get-all-rock-paths
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      rock-paths: $ {{ steps.filters.outputs.changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: ${{ needs.get-all-rock-paths.outputs.paths}}

  test-rock:
    name: Integrate workflow for ${{ matrix.rock-dir }}
    needs: changes
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rock-dir: ${{ fromJson(needs.changes.outputs.rock-paths)}}
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/integrate_rock.yaml@kf-5024-feat-integrate-rock
    with:
      rock-dir: ${{ matrix.rock-dir }}
