name: Get ROCKs modified

on:
  workflow_call:
    outputs:
      paths:
        description: Get paths for ROCKs modified
        value: ${{ jobs.rock-dirs-with-changes.outputs.rock_paths }}

jobs:
  get-all-rock-paths:
    name: Get all rockcraft.yaml paths
    runs-on: ubuntu-22.04
    outputs:
      paths: ${{ steps.find.outputs.paths}}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Get all rockcraft.yaml paths using find
        id: find
        run: |
          paths=$(find ./ -name "rockcraft.yaml" -printf "%h:\n  - '%h/**'\n" | sed 's/\.\///g')
          echo "Paths found:"
          echo "${paths}"
          # Passing multi-line string to output requires the use of a delimiter
          echo "paths<<EOF" >> $GITHUB_OUTPUT
          echo "${paths}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  rock-dirs-with-changes:
    name: Get paths for ROCKs modified by PR
    needs: get-all-rock-paths
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      rock_paths: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: ${{ needs.get-all-rock-paths.outputs.paths}}
